use crate::borrowck::cfg::{ConstraintSource, OutlivesConstraint, RegionGraph, RegionId};
use crate::span::Error;

// Phase L4: outlives solver. The graph contains two kinds of edges:
//   * Declared facts — `WhereClause` and `StaticOutlives`. The user /
//     language guarantees these hold.
//   * Requirements — `FnReturn`, `CallArg`, `CallReturn`, `Assign`,
//     `Reborrow`. Generated by body operations.
//
// Region kinds for the solver:
//   * Fixed: `'static` plus regions in `sig_named` / `sig_inferred`.
//     Their values are picked by the caller (universally quantified),
//     so the body can't constrain them — it must satisfy them.
//   * Body-fresh: every other region. The solver picks values for
//     these to satisfy the constraints. As long as a satisfying
//     assignment exists, the body type-checks.
//
// Soundness shortcut taken here: a required edge between a body-fresh
// region and any other is treated as trivially satisfiable — the
// body-fresh region can be assigned to whatever value satisfies. This
// is loose (real Rust does proper region-variable inference with
// constraint propagation) but correct in the "won't reject valid
// programs" sense. Required edges *between two fixed regions* are
// checked against the closure of declared facts; failure there means
// no caller-provided values can satisfy the body's needs.
//
// The first violation becomes the error returned. Diagnostics name
// the requirement's source op (the span on the constraint) and
// suggest the missing where-clause when both sides are sig-named.
pub fn solve(graph: &RegionGraph, fn_path: &Vec<String>, file: &str) -> Result<(), Error> {
    let n = max_region(graph) + 1;
    let fixed: Vec<bool> = build_fixed_set(graph, n);
    // closure[sup][sub] = true iff sup outlives sub is implied by the
    // declared facts. Reflexive (sup outlives sup) is always true.
    let mut closure: Vec<Vec<bool>> = vec![vec![false; n as usize]; n as usize];
    let mut i = 0;
    while i < n {
        closure[i as usize][i as usize] = true;
        i += 1;
    }
    for c in &graph.outlives {
        if is_declared(c.source) {
            closure[c.sup as usize][c.sub as usize] = true;
        }
    }
    // Floyd-Warshall transitive closure. Pocket-rust fns have few
    // regions (<20 typically), so n³ is fine.
    let mut k = 0;
    while k < n {
        let mut i2 = 0;
        while i2 < n {
            let mut j = 0;
            while j < n {
                if closure[i2 as usize][k as usize] && closure[k as usize][j as usize] {
                    closure[i2 as usize][j as usize] = true;
                }
                j += 1;
            }
            i2 += 1;
        }
        k += 1;
    }
    // Verify each requirement whose endpoints are both fixed.
    for c in &graph.outlives {
        if is_declared(c.source) {
            continue;
        }
        if !fixed[c.sup as usize] || !fixed[c.sub as usize] {
            // At least one endpoint is body-fresh — the solver can
            // pick its value to satisfy. Skip.
            continue;
        }
        if !closure[c.sup as usize][c.sub as usize] {
            return Err(diag(c, graph, fn_path, file));
        }
    }
    Ok(())
}

fn build_fixed_set(graph: &RegionGraph, n: u32) -> Vec<bool> {
    let mut fixed = vec![false; n as usize];
    fixed[crate::borrowck::cfg::STATIC_REGION as usize] = true;
    for (_, r) in &graph.sig_named {
        if (*r as usize) < fixed.len() {
            fixed[*r as usize] = true;
        }
    }
    for (_, r) in &graph.sig_inferred {
        if (*r as usize) < fixed.len() {
            fixed[*r as usize] = true;
        }
    }
    fixed
}

fn is_declared(s: ConstraintSource) -> bool {
    matches!(
        s,
        ConstraintSource::WhereClause | ConstraintSource::StaticOutlives
    )
}

fn max_region(graph: &RegionGraph) -> RegionId {
    let mut m: RegionId = 0;
    for (_, r) in &graph.sig_named {
        if *r > m {
            m = *r;
        }
    }
    for (_, r) in &graph.sig_inferred {
        if *r > m {
            m = *r;
        }
    }
    for c in &graph.outlives {
        if c.sup > m {
            m = c.sup;
        }
        if c.sub > m {
            m = c.sub;
        }
    }
    m
}

fn diag(c: &OutlivesConstraint, graph: &RegionGraph, fn_path: &Vec<String>, file: &str) -> Error {
    let sup_name = region_display(c.sup, graph);
    let sub_name = region_display(c.sub, graph);
    let what = match c.source {
        ConstraintSource::FnReturn => "returned reference's lifetime",
        ConstraintSource::CallArg => "argument lifetime",
        ConstraintSource::CallReturn => "call result's lifetime",
        ConstraintSource::Assign => "assigned value's lifetime",
        ConstraintSource::Reborrow => "reborrowed reference's lifetime",
        // Declared sources never reach diag (filtered in `solve`).
        ConstraintSource::WhereClause | ConstraintSource::StaticOutlives => "lifetime",
    };
    let suggestion = match (named_region(c.sup, graph), named_region(c.sub, graph)) {
        (Some(a), Some(b)) if a != b => format!(
            " (consider adding `where '{}: '{}` to `{}`)",
            a,
            b,
            crate::typeck::place_to_string(fn_path),
        ),
        _ => String::new(),
    };
    Error {
        file: file.to_string(),
        message: format!(
            "{} `{}` does not outlive `{}`{}",
            what, sup_name, sub_name, suggestion,
        ),
        span: c.span.copy(),
    }
}

fn region_display(r: RegionId, graph: &RegionGraph) -> String {
    if r == crate::borrowck::cfg::STATIC_REGION {
        return "'static".to_string();
    }
    for (n, r2) in &graph.sig_named {
        if *r2 == r {
            return format!("'{}", n);
        }
    }
    for (id, r2) in &graph.sig_inferred {
        if *r2 == r {
            return format!("'_#{}", id);
        }
    }
    format!("'<r{}>", r)
}

fn named_region(r: RegionId, graph: &RegionGraph) -> Option<String> {
    if r == crate::borrowck::cfg::STATIC_REGION {
        return Some("static".to_string());
    }
    for (n, r2) in &graph.sig_named {
        if *r2 == r {
            return Some(n.clone());
        }
    }
    None
}
