use crate::borrowck::cfg::{ConstraintSource, OutlivesConstraint, RegionGraph, RegionId};
use crate::span::Error;

// Phase L4: outlives solver. Two kinds of edges live in the graph:
//   * Declared facts — `WhereClause` and `StaticOutlives`. The user /
//     language guarantees these hold.
//   * Requirements — `FnReturn`, `CallArg`, `CallReturn`, `Assign`,
//     `Reborrow`. Generated by body operations.
//
// Region kinds:
//   * Fixed — `'static` plus regions in `sig_named` / `sig_inferred`.
//     The caller picks the value (universally quantified); the body
//     must satisfy the constraints for any caller-provided substitution.
//   * Body-fresh — every other region. The solver picks the value;
//     constraints involving them are satisfiable as long as some
//     assignment exists that makes everything consistent.
//
// Algorithm (rt6#4): two transitive closures over the region graph,
// each via Floyd-Warshall (n is small):
//   * `c_d` — closure of declared facts only. The set of (sup, sub)
//     pairs the caller / language has guaranteed.
//   * `c_full` — closure of ALL edges (declared + required), with
//     body-fresh regions acting as transit nodes that link sig-fixed
//     endpoints. Any (sup, sub) pair in `c_full` is a relation the
//     body's operations imply must hold.
//
// Verification: for every sig-fixed pair (S1, S2), `c_full` ⊆ `c_d`.
// If `c_full[S1][S2]` but `!c_d[S1][S2]`, the body asserts a relation
// the declared facts don't support — error. Catches transitive sig-only
// requirements that route through body-fresh middles (rt6#4).
//
// Diagnostic attribution: pick a required edge that contributes to
// the failed pair (its `sup` reachable from S1, S2 reachable from its
// `sub` in `c_full`). The edge's span tells the user where the
// problematic op is; the suggestion proposes the missing where-clause
// when both sides are sig-named.
pub fn solve(graph: &RegionGraph, fn_path: &Vec<String>, file: &str) -> Result<(), Error> {
    let n = max_region(graph) + 1;
    let fixed: Vec<bool> = build_fixed_set(graph, n);
    let c_d = closure_over(graph, n, |s| is_declared(s));
    let c_full = closure_over(graph, n, |_| true);
    // Sig-fixed pair check: any c_full edge missing in c_d is a
    // body-side requirement the declared facts don't support.
    let mut i: u32 = 0;
    while i < n {
        if fixed[i as usize] {
            let mut j: u32 = 0;
            while j < n {
                if fixed[j as usize] && i != j {
                    if c_full[i as usize][j as usize] && !c_d[i as usize][j as usize] {
                        return Err(diag_for_pair(graph, i, j, &c_full, fn_path, file));
                    }
                }
                j += 1;
            }
        }
        i += 1;
    }
    Ok(())
}

// Build the n×n transitive closure of edges in `graph.outlives`
// matching `pred(source)`. Identity (sup→sup) is always true.
fn closure_over(
    graph: &RegionGraph,
    n: u32,
    pred: impl Fn(ConstraintSource) -> bool,
) -> Vec<Vec<bool>> {
    let mut c: Vec<Vec<bool>> = vec![vec![false; n as usize]; n as usize];
    let mut i: u32 = 0;
    while i < n {
        c[i as usize][i as usize] = true;
        i += 1;
    }
    for con in &graph.outlives {
        if pred(con.source) {
            c[con.sup as usize][con.sub as usize] = true;
        }
    }
    // Floyd-Warshall.
    let mut k: u32 = 0;
    while k < n {
        let mut a: u32 = 0;
        while a < n {
            let mut b: u32 = 0;
            while b < n {
                if c[a as usize][k as usize] && c[k as usize][b as usize] {
                    c[a as usize][b as usize] = true;
                }
                b += 1;
            }
            a += 1;
        }
        k += 1;
    }
    c
}

fn build_fixed_set(graph: &RegionGraph, n: u32) -> Vec<bool> {
    let mut fixed = vec![false; n as usize];
    fixed[crate::borrowck::cfg::STATIC_REGION as usize] = true;
    for (_, r) in &graph.sig_named {
        if (*r as usize) < fixed.len() {
            fixed[*r as usize] = true;
        }
    }
    for (_, r) in &graph.sig_inferred {
        if (*r as usize) < fixed.len() {
            fixed[*r as usize] = true;
        }
    }
    fixed
}

fn is_declared(s: ConstraintSource) -> bool {
    matches!(
        s,
        ConstraintSource::WhereClause | ConstraintSource::StaticOutlives
    )
}

fn max_region(graph: &RegionGraph) -> RegionId {
    let mut m: RegionId = 0;
    for (_, r) in &graph.sig_named {
        if *r > m {
            m = *r;
        }
    }
    for (_, r) in &graph.sig_inferred {
        if *r > m {
            m = *r;
        }
    }
    for c in &graph.outlives {
        if c.sup > m {
            m = c.sup;
        }
        if c.sub > m {
            m = c.sub;
        }
    }
    m
}

// Diagnostic for a sig-fixed pair (s1, s2) where c_full has it but
// c_d doesn't. Find a required edge that contributes to the chain
// s1 → … → s2 in c_full and use its span. A "contributing" edge has
// `c_full[s1][edge.sup]` and `c_full[edge.sub][s2]` — i.e., it lies on
// some path from s1 to s2.
fn diag_for_pair(
    graph: &RegionGraph,
    s1: u32,
    s2: u32,
    c_full: &Vec<Vec<bool>>,
    fn_path: &Vec<String>,
    file: &str,
) -> Error {
    let blame: Option<&OutlivesConstraint> = graph.outlives.iter().find(|c| {
        !is_declared(c.source)
            && c_full
                .get(s1 as usize)
                .and_then(|row| row.get(c.sup as usize))
                .copied()
                .unwrap_or(false)
            && c_full
                .get(c.sub as usize)
                .and_then(|row| row.get(s2 as usize))
                .copied()
                .unwrap_or(false)
    });
    let what = blame.map(|b| source_label(b.source)).unwrap_or("lifetime");
    let span = blame
        .map(|b| b.span.copy())
        .unwrap_or_else(|| crate::span::Span::new(crate::span::Pos::new(1, 1), crate::span::Pos::new(1, 1)));
    let s1_name = region_display(s1, graph);
    let s2_name = region_display(s2, graph);
    let suggestion = match (named_region(s1, graph), named_region(s2, graph)) {
        (Some(a), Some(b)) if a != b => format!(
            " (consider adding `where '{}: '{}` to `{}`)",
            a,
            b,
            crate::typeck::place_to_string(fn_path),
        ),
        _ => String::new(),
    };
    Error {
        file: file.to_string(),
        message: format!(
            "{} `{}` does not outlive `{}`{}",
            what, s1_name, s2_name, suggestion,
        ),
        span,
    }
}

fn source_label(s: ConstraintSource) -> &'static str {
    match s {
        ConstraintSource::FnReturn => "returned reference's lifetime",
        ConstraintSource::CallArg => "argument lifetime",
        ConstraintSource::CallReturn => "call result's lifetime",
        ConstraintSource::Assign => "assigned value's lifetime",
        ConstraintSource::Reborrow => "reborrowed reference's lifetime",
        ConstraintSource::WhereClause | ConstraintSource::StaticOutlives => "lifetime",
    }
}

fn region_display(r: RegionId, graph: &RegionGraph) -> String {
    if r == crate::borrowck::cfg::STATIC_REGION {
        return "'static".to_string();
    }
    for (n, r2) in &graph.sig_named {
        if *r2 == r {
            return format!("'{}", n);
        }
    }
    for (id, r2) in &graph.sig_inferred {
        if *r2 == r {
            return format!("'_#{}", id);
        }
    }
    format!("'<r{}>", r)
}

fn named_region(r: RegionId, graph: &RegionGraph) -> Option<String> {
    if r == crate::borrowck::cfg::STATIC_REGION {
        return Some("static".to_string());
    }
    for (n, r2) in &graph.sig_named {
        if *r2 == r {
            return Some(n.clone());
        }
    }
    None
}
